### ISSUE TITLE
Need to vote itself firstly when timeout

### ISSUE THREAD

**Issue by Sen-Deng** [ongardie/raft.tla#10]
I think that there are some issues about Timeout(i) transition. When one server timeout and starts a new election, it is supposed to voted itself firstly.  It should set votedFor[i] = i and votesGranted[i] = {i}.

**Comment by fritzalder** [comment]
Not the author but note the comment right before the votedFor' line in Timeout:
`              \* Most implementations would probably just set the local vote
              \* atomically, but messaging localhost for it is weaker. `
If you look at RequestVote, candidates will send themselves a request to vote for itself and then respond. It does bloat up the states a little bit and I am somewhat convinced that you could do it atomically, but this will still work.

**Comment by Sen-Deng** [comment]
Thanks! I'll close the issue.
